### ISSUE TITLE
コンストラクタの修正提案

### ISSUE THREAD

**Issue by mantaroh** [unimal-jp/spearly-sdk-js#56]
Astro + Spearly CMS を利用してみて、数行で連携することができました！

実際に使ってみて、以下の点が気になったのでコンストラクタを変えたいと思いますが、いかがでしょうか？

# コンストラクタ

## 現在の仕様

```
const apiClient = new SpearlyApiClient(SPEARLY_DOMAIN, API_KEY)
```

### 気になる点

- Spearly CMS の API 説明ドキュメントでは以下のように URL と 認証ヘッダーのコピペとなっているため、ドメイン・APIキーの指定時に気づかずにコピペしてしまった。(API 説明ドキュメントでは、「API キーはこちらです」と認証ヘッダが書かれていたもので…
![image](https://user-images.githubusercontent.com/3241026/203674319-a3c93def-d337-41a0-9151-c2395ebdfe69.png)

- ButterCMS/Contentful の SDK は API キーだけの指定となっていたので、利用者としてドメイン指定しなくても良さそう。

## 変更提案

SpearliApiClient の引数を以下のように指定する

1. APIキー・ドメインではなく、API認証ヘッダ・API URL を指定するようにする

```
const apiClient = new SpearlyApiClient(SPEARLY_API_URL, API_AUTHORIZE_HEADER)
```

- SPEARLY_DOMAIN -> SPEARLY_API_URL (Optional) : Spearly CMS のドキュメントからコピペできるフォーマットにしたい
- API_KEY -> API_AUTHORIZE_HEADER

2. ドメインを オプション指定とする

```
const apiClient = new SpearlyApiClient(API_KEY)
```

- SPEARLY_DOMAIN -> SPEARLY_API_URL (Optional) : Spearly CMS のドキュメントからコピペできるフォーマットにしたい

※この場合は、API_KEY を設定からコピペしてくださいというやり方で誘導できるので、わかりやすいかもしれません。

**Comment by akoarum** [comment]
@mantaroh 
`SPEARLY_DOMAIN` → `SPEARLY_API_URL (optional)` は良さそうだなと思いますが、APIキーだけ渡せばすぐ使えるようにしたい意図があるので、API_KEYはヘッダにしたくないなと思っています。

そしてそもそもとして、改めて見ていると埋め込み方法のAPIキーに `Authorization: Bearer` が含まれてしまっていることがそもそものミスリードな気がするので、埋め込み方法のページの記述を変更しつつ、「2. ドメインを オプション指定とする」の対応を取るのが良さそうかなと感じています。

**Comment by mantaroh** [comment]
@akoarum 

ありがとうございますー！

> 改めて見ていると埋め込み方法のAPIキーに Authorization: Bearer が含まれてしまっていることがそもそものミスリードな気がする

そうですよね。こちらは、公式ドキュメントを修正してもらえるか問い合わせてみます！

> 「2. ドメインを オプション指定とする」の対応を取るのが良さそうかなと感じています。

こちらはオプションとして指定するように修正してみようと思います 🙇🏼‍♂️
