### ISSUE TITLE
Axios Error 発生時の例外の型変更提案

### ISSUE THREAD

**Issue by mantaroh** [unimal-jp/spearly-sdk-js#75]
## 提案内容

axios でエラーが発生した場合は、そのレスポンスを含む AxiosError 型で返すように変更するのはいかがでしょうか？

## 修正内容

[変更内容](https://github.com/unimal-jp/spearly-sdk-js/compare/main...dcfb3bea21f90eeccdea035848d042b2d3dc6865)

## 背景

`spearly-sdk-js` を使っていて、200 以外のエラーが発生すると Error が返ってきます。  
現在のコードでは、この AxiosError から派生した Error を作成しているので、response データ等は削除されて送られてきます。  
https://github.com/unimal-jp/spearly-sdk-js/blob/93e4d7ea8a65fa1b5d190657d3f9a5bb61475532/src/spearly-api-client/SpearlyApiClient.ts#L65

もし、クライアント側でステータスをもとに処理を分けたいケースがあり、その場合エラーメッセージに含まれるステータスコードを解析する必要があります。(エラーメッセージ例： `Error: AxiosError: Request failed with status code 401`)

### ステータスで処理を分けたいユースケース  
例：フォームの場合  
回答日が過ぎているとステータスコード `409 (Conflict)` で返ってきますが、フォームの Validation エラーの場合は `422 (Unprocessable Entity)` となって、ステータスコード別にエラーを変えたい場合

例：コンテンツ取得の場合  
通常 `200 (OK)` で返ってくるが、利用帯域制限を超えた場合は `200 (OK)` 以外となって、エラーメッセージを表示させたい場合

**Comment by mantaroh** [comment]
@akoarum 

こちらの修正内容で、型を `Error` ではなく発生したときのエラーの型のまま送っていただきたいと思うのですが、修正内容どう思いますか？
(sdk-js で独自の Error 型を定義しても良さそうかなーとも思いました)

**Comment by akoarum** [comment]
@mantaroh 

ご提案ありがとうございます！
とても良さそうです。

元々axiosを使用していなかった頃の名残で、手付かずのままになっていました。

**Comment by mantaroh** [comment]
@akoarum 

ありがとうございますー！
修正 PR を出しましたので、ご確認よろしくおねがいします！

https://github.com/unimal-jp/spearly-sdk-js/pull/76
